# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Act < Formula
  desc "Run GitHub Actions locally"
  homepage "https://github.com/nektos/act"
  version "0.2.19"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nektos/act/releases/download/v0.2.19/act_Darwin_x86_64.tar.gz"
    sha256 "d9d82ed3d2bb3177b83e75dd3ced3403f47625457f4555787e0dd31e476ac181"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nektos/act/releases/download/v0.2.19/act_Linux_x86_64.tar.gz"
    sha256 "be52d1cb8cc5d2f9313ed1001807911ba3fed7a8201b96cc930ddd0ebef21dff"
  end

  def install
    bin.install "act"
  end

  test do
    system "#{bin}/act --version"
  end
end
