# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Act < Formula
  desc "Run GitHub Actions locally"
  homepage "https://github.com/nektos/act"
  version "0.2.18"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nektos/act/releases/download/v0.2.18/act_Darwin_x86_64.tar.gz"
    sha256 "616d04b96375f0a993c7dd300f3f45521a2382f5d4940ae50ccef517469a9e6e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nektos/act/releases/download/v0.2.18/act_Linux_x86_64.tar.gz"
    sha256 "51e4c2f9edda514c2c5c5fa10a9528d683dad131a773595a65bf6039623779ee"
  end

  def install
    bin.install "act"
  end

  test do
    system "#{bin}/act --version"
  end
end
